;; Possible Bank Info ;;
;; Based only on observing gameplay ;;

BANK_OVERWORLD       = $03

BANK_LEVELUP         = $05	; battle message code

BANK_ENEMY_CHR       = $07

BANK_TITLE           = $09
BANK_MENUTEXT        = $09
BANK_BATTLESPRITES   = $09
BANK_PORTRAITS       = $09

BANK_OVERWORLD_DATA  = $0A

BANK_BATTLELOAD      = $0B	; battle graphics code

BANK_BATTLE          = $0C	; battle main code

BANK_MUSIC           = $0D

BANK_INTRO           = $0E
BANK_MENU            = $0E

;; BGM list
BGM_prelude	= $41
BGM_chocobo	= $43
BGM_feild	= $44

; $62FE = set to #$5A if save slot is valid
SLOT_VALID	= $5A
